# Generated by Django 2.1.2 on 2018-11-02 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='invalid number', regex='^\\d{11}$')])),
                ('Address', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(on_delete='cascade', to='listing.Categories')),
            ],
        ),
    ]
