# Generated by Django 2.1.2 on 2018-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Category',
        ),
        migrations.AddField(
            model_name='listing',
            name='Category',
            field=models.ManyToManyField(to='listing.Categories'),
        ),
    ]
