# Generated by Django 2.1.2 on 2018-11-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20181102_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
